# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-04 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpatternset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textpatternset',
            name='owner_sessionid',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
