# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 11:59


import cms.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_blogindexpage_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=wagtail.core.fields.StreamField([(b'heading', wagtail.core.blocks.CharBlock(classname=b'')), (b'paragraph', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'image_caption', wagtail.core.blocks.CharBlock(classname=b'richtext-caption')), (b'image_and_text', wagtail.core.blocks.StructBlock([(b'text', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock()), (b'alignment', cms.models.ImageFormatChoiceBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='content',
            field=wagtail.core.fields.StreamField([(b'heading', wagtail.core.blocks.CharBlock(classname=b'')), (b'paragraph', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'image_caption', wagtail.core.blocks.CharBlock(classname=b'richtext-caption')), (b'image_and_text', wagtail.core.blocks.StructBlock([(b'text', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock()), (b'alignment', cms.models.ImageFormatChoiceBlock())]))]),
        ),
        migrations.AlterField(
            model_name='richtextpage',
            name='content',
            field=wagtail.core.fields.StreamField([(b'heading', wagtail.core.blocks.CharBlock(classname=b'')), (b'paragraph', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'image_caption', wagtail.core.blocks.CharBlock(classname=b'richtext-caption')), (b'image_and_text', wagtail.core.blocks.StructBlock([(b'text', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock()), (b'alignment', cms.models.ImageFormatChoiceBlock())]))]),
        ),
    ]
