# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 17:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20180509_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title_fr',
            field=models.CharField(blank=True, default=b'', help_text="The page title as you'd like it to be seen by the public", max_length=255, verbose_name=b'Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_fr',
            field=models.CharField(blank=True, default=b'', help_text="The page title as you'd like it to be seen by the public", max_length=255, verbose_name=b'Title'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='title_fr',
            field=models.CharField(blank=True, default=b'', help_text="The page title as you'd like it to be seen by the public", max_length=255, verbose_name=b'Title'),
        ),
        migrations.AddField(
            model_name='richtextpage',
            name='title_fr',
            field=models.CharField(blank=True, default=b'', help_text="The page title as you'd like it to be seen by the public", max_length=255, verbose_name=b'Title'),
        ),
    ]
