#!/bin/bash

KILN_OUT_PATH="/django_media/kiln_out"

# The django app will create the kiln_out folder.
# Because it has the right django user.
# If we create it here, we'll cause permission issues.
# mkdir -p $KILN_OUT_PATH

cd /app
if [ ! -f "kiln_out" ]; then
  ln -s $KILN_OUT_PATH
fi

# We just want the container to remain available.
# Less wasteful to use docker exec than docker run.
sleep infinity
