#!/bin/bash

KILN_OUT_PATH="/django_media/kiln_out"

mkdir -p $KILN_OUT_PATH
cd /app
if [ ! -f "$KILN_OUT_PATH" ]; then
  ln -s $KILN_OUT_PATH kiln_out
fi

# We just want the container to remain available.
# Less wasteful to use docker exec than docker run.
sleep infinity
