# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 16:42


import cms.models
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20160526_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'image_caption', wagtail.wagtailcore.blocks.CharBlock(classname=b'richtext-caption')), (b'image_and_caption', wagtail.wagtailcore.blocks.StructBlock([(b'images', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.RichTextBlock())])), (b'image_and_text', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.RichTextBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.RichTextBlock()), (b'alignment', cms.models.ImageFormatChoiceBlock())]))]),
        ),
    ]
