# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 22:18


import cms.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20180509_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_fr',
            field=wagtail.core.fields.StreamField([(b'heading', wagtail.core.blocks.CharBlock(classname=b'')), (b'paragraph', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'image_caption', wagtail.core.blocks.CharBlock(classname=b'richtext-caption')), (b'image_and_caption', wagtail.core.blocks.StructBlock([(b'images', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock())])), (b'image_and_text', wagtail.core.blocks.StructBlock([(b'text', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock()), (b'alignment', cms.models.ImageFormatChoiceBlock())]))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_fr',
            field=wagtail.core.fields.StreamField([(b'heading', wagtail.core.blocks.CharBlock(classname=b'')), (b'paragraph', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'image_caption', wagtail.core.blocks.CharBlock(classname=b'richtext-caption')), (b'image_and_caption', wagtail.core.blocks.StructBlock([(b'images', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock())])), (b'image_and_text', wagtail.core.blocks.StructBlock([(b'text', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock()), (b'alignment', cms.models.ImageFormatChoiceBlock())]))], blank=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='content_fr',
            field=wagtail.core.fields.StreamField([(b'heading', wagtail.core.blocks.CharBlock(classname=b'')), (b'paragraph', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'image_caption', wagtail.core.blocks.CharBlock(classname=b'richtext-caption')), (b'image_and_caption', wagtail.core.blocks.StructBlock([(b'images', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock())])), (b'image_and_text', wagtail.core.blocks.StructBlock([(b'text', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock()), (b'alignment', cms.models.ImageFormatChoiceBlock())]))], blank=True),
        ),
        migrations.AddField(
            model_name='richtextpage',
            name='content_fr',
            field=wagtail.core.fields.StreamField([(b'heading', wagtail.core.blocks.CharBlock(classname=b'')), (b'paragraph', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'image_caption', wagtail.core.blocks.CharBlock(classname=b'richtext-caption')), (b'image_and_caption', wagtail.core.blocks.StructBlock([(b'images', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock())])), (b'image_and_text', wagtail.core.blocks.StructBlock([(b'text', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'caption', wagtail.core.blocks.RichTextBlock()), (b'alignment', cms.models.ImageFormatChoiceBlock())]))], blank=True),
        ),
    ]
