# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-25 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20180509_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='redirect_url',
            field=models.CharField(blank=True, default=b'', help_text='Absolute or relative URL to the web page this page will redirect to', max_length=255, verbose_name=b'Redirect URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='redirect_url',
            field=models.CharField(blank=True, default=b'', help_text='Absolute or relative URL to the web page this page will redirect to', max_length=255, verbose_name=b'Redirect URL'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='redirect_url',
            field=models.CharField(blank=True, default=b'', help_text='Absolute or relative URL to the web page this page will redirect to', max_length=255, verbose_name=b'Redirect URL'),
        ),
        migrations.AddField(
            model_name='richtextpage',
            name='redirect_url',
            field=models.CharField(blank=True, default=b'', help_text='Absolute or relative URL to the web page this page will redirect to', max_length=255, verbose_name=b'Redirect URL'),
        ),
    ]
