# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('cms', '0012_auto_20180725_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
