# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 23:34
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_blogpost_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image_caption', wagtail.wagtailcore.blocks.CharBlock(classname='richtext-caption')), ('image_and_caption', wagtail.wagtailcore.blocks.StructBlock((('images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock())))), ('image_and_text', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', cms.models.ImageFormatChoiceBlock())))))),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_fr',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image_caption', wagtail.wagtailcore.blocks.CharBlock(classname='richtext-caption')), ('image_and_caption', wagtail.wagtailcore.blocks.StructBlock((('images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock())))), ('image_and_text', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', cms.models.ImageFormatChoiceBlock()))))), blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='redirect_url',
            field=models.CharField(blank=True, default='', help_text='Absolute or relative URL to the web page this page will redirect to', max_length=255, verbose_name='Redirect URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_fr',
            field=models.CharField(blank=True, default='', help_text="The page title as you'd like it to be seen by the public", max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image_and_caption', wagtail.wagtailcore.blocks.StructBlock((('images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock())))))),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_fr',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image_caption', wagtail.wagtailcore.blocks.CharBlock(classname='richtext-caption')), ('image_and_caption', wagtail.wagtailcore.blocks.StructBlock((('images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock())))), ('image_and_text', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', cms.models.ImageFormatChoiceBlock()))))), blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='redirect_url',
            field=models.CharField(blank=True, default='', help_text='Absolute or relative URL to the web page this page will redirect to', max_length=255, verbose_name='Redirect URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_fr',
            field=models.CharField(blank=True, default='', help_text="The page title as you'd like it to be seen by the public", max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image_caption', wagtail.wagtailcore.blocks.CharBlock(classname='richtext-caption')), ('image_and_caption', wagtail.wagtailcore.blocks.StructBlock((('images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock())))), ('image_and_text', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', cms.models.ImageFormatChoiceBlock())))))),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='content_fr',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image_caption', wagtail.wagtailcore.blocks.CharBlock(classname='richtext-caption')), ('image_and_caption', wagtail.wagtailcore.blocks.StructBlock((('images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock())))), ('image_and_text', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', cms.models.ImageFormatChoiceBlock()))))), blank=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='redirect_url',
            field=models.CharField(blank=True, default='', help_text='Absolute or relative URL to the web page this page will redirect to', max_length=255, verbose_name='Redirect URL'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='title_fr',
            field=models.CharField(blank=True, default='', help_text="The page title as you'd like it to be seen by the public", max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='richtextpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image_caption', wagtail.wagtailcore.blocks.CharBlock(classname='richtext-caption')), ('image_and_caption', wagtail.wagtailcore.blocks.StructBlock((('images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock())))), ('image_and_text', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', cms.models.ImageFormatChoiceBlock())))))),
        ),
        migrations.AlterField(
            model_name='richtextpage',
            name='content_fr',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image_caption', wagtail.wagtailcore.blocks.CharBlock(classname='richtext-caption')), ('image_and_caption', wagtail.wagtailcore.blocks.StructBlock((('images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock())))), ('image_and_text', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', cms.models.ImageFormatChoiceBlock()))))), blank=True),
        ),
        migrations.AlterField(
            model_name='richtextpage',
            name='redirect_url',
            field=models.CharField(blank=True, default='', help_text='Absolute or relative URL to the web page this page will redirect to', max_length=255, verbose_name='Redirect URL'),
        ),
        migrations.AlterField(
            model_name='richtextpage',
            name='title_fr',
            field=models.CharField(blank=True, default='', help_text="The page title as you'd like it to be seen by the public", max_length=255, verbose_name='Title'),
        ),
    ]
