# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 20:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedtoken',
            name='is_rubric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotatedtoken',
            name='manuscript',
            field=models.CharField(default='unspecified', max_length=30),
        ),
        migrations.AddField(
            model_name='annotatedtoken',
            name='section_name',
            field=models.CharField(default='unspecified', max_length=100),
        ),
        migrations.AlterField(
            model_name='annotatedtoken',
            name='location',
            field=models.CharField(help_text='location id for the seg comprising this token', max_length=20),
        ),
        migrations.AlterField(
            model_name='annotatedtoken',
            name='pos',
            field=models.CharField(help_text='part of speech', max_length=30),
        ),
    ]
