# Generated by Django 2.2.4 on 2019-10-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0007_annotatedtoken_section_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedtoken',
            name='verse_cat',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annotatedtoken',
            name='section_number',
            field=models.CharField(max_length=10),
        ),
    ]
