# Generated by Django 2.2.4 on 2019-10-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0010_searchfacet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchfacet',
            options={'ordering': ['display_rank']},
        ),
        migrations.RemoveField(
            model_name='searchfacet',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='searchfacet',
            name='display_rank',
            field=models.IntegerField(default=0),
        ),
    ]
