# Generated by Django 2.2.4 on 2019-10-16 23:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0011_auto_20191007_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocompleteToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('lemma', models.CharField(max_length=30)),
            ],
            managers=[
                ('from_kwic', django.db.models.manager.Manager()),
            ],
        ),
    ]
