# Generated by Django 2.2.4 on 2019-10-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0012_autocompletetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocompletetoken',
            name='type',
        ),
        migrations.AddField(
            model_name='searchfacet',
            name='whitelist',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='searchfacet',
            name='key',
            field=models.CharField(choices=[('manuscript_number', 'manuscript_number'), ('lemma', 'lemma'), ('form', 'form'), ('section_number', 'section_number'), ('pos', 'pos'), ('is_rubric', 'is_rubric'), ('verse_cat', 'verse_cat'), ('speech_cat', 'speech_cat')], max_length=32, unique=True),
        ),
    ]
