# Generated by Django 2.2.4 on 2019-10-22 18:19

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0014_auto_20191021_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfacet',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='tick this to hide the facet from the search page'),
        ),
        migrations.AlterField(
            model_name='searchfacet',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='a more verbose description of the facet to appear on a separate help page.'),
        ),
        migrations.AlterField(
            model_name='searchfacet',
            name='display_rank',
            field=models.IntegerField(default=0, help_text='the display order of this facet on the search page, lower numbers appear on top. NOT YET IMPLEMENTED.'),
        ),
        migrations.AlterField(
            model_name='searchfacet',
            name='label',
            field=models.CharField(help_text='The heading for this facet on the search page', max_length=32),
        ),
        migrations.AlterField(
            model_name='searchfacet',
            name='tooltip',
            field=models.CharField(blank=True, help_text='Once short sentence to describe this facet to the users.', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchfacet',
            name='whitelist',
            field=models.TextField(blank=True, default='one facet option per line. If empty all options are visible, otherwise only the supplied options are visible.'),
        ),
    ]
