# Generated by Django 2.2.4 on 2019-10-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0016_auto_20191022_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfacet',
            name='tooltip',
            field=models.CharField(blank=True, help_text='One short sentence to describe this facet to the users.', max_length=255),
        ),
    ]
