# Generated by Django 2.2.4 on 2019-10-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0017_auto_20191022_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedtoken',
            name='lemmapos',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='searchfacet',
            name='key',
            field=models.CharField(choices=[('manuscript_number', 'manuscript_number'), ('lemma', 'lemma'), ('form', 'form'), ('section_number', 'section_number'), ('pos', 'pos'), ('lemmapos', 'lemmapos'), ('is_rubric', 'is_rubric'), ('verse_cat', 'verse_cat'), ('speech_cat', 'speech_cat')], max_length=32, unique=True),
        ),
    ]
