# Generated by Django 2.2.4 on 2019-10-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0018_auto_20191022_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfacet',
            name='limit',
            field=models.IntegerField(default=-2, help_text='maximum number of options to show under this facet. Special numbers: -1 unlimited, -2 default preset.'),
        ),
    ]
