# Generated by Django 2.2.12 on 2020-04-15 16:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0019_searchfacet_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(default='', max_length=30)),
                ('forms', models.CharField(blank=True, default='', max_length=300)),
                ('pos', models.CharField(blank=True, default='', max_length=30)),
                ('name_type', models.CharField(blank=True, default='', max_length=30)),
            ],
            managers=[
                ('from_kwic', django.db.models.manager.Manager()),
            ],
        ),
    ]
