# Generated by Django 2.2.12 on 2020-04-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0020_lemma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfacet',
            name='key',
            field=models.CharField(choices=[('manuscript_number', 'manuscript_number'), ('lemma', 'lemma'), ('form', 'form'), ('section_number', 'section_number'), ('pos', 'pos'), ('lemmapos', 'lemmapos'), ('is_rubric', 'is_rubric'), ('verse_cat', 'verse_cat'), ('speech_cat', 'speech_cat'), ('name_type', 'name_type')], max_length=32, unique=True),
        ),
    ]
