# Generated by Django 2.2.4 on 2019-09-17 18:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0003_annotatedtoken_lemmapos'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='annotatedtoken',
            managers=[
                ('from_kwic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='annotatedtoken',
            name='is_rubric',
        ),
        migrations.RemoveField(
            model_name='annotatedtoken',
            name='lemmapos',
        ),
        migrations.RemoveField(
            model_name='annotatedtoken',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='annotatedtoken',
            name='section_name',
        ),
        migrations.AlterField(
            model_name='annotatedtoken',
            name='following',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='annotatedtoken',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='annotatedtoken',
            name='pos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='annotatedtoken',
            name='preceding',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='annotatedtoken',
            name='token_number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
