# Generated by Django 2.2.4 on 2019-10-06 23:28

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0009_annotatedtoken_speech_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFacet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.CharField(choices=[('manuscript_number', 'manuscript_number'), ('lemma', 'lemma'), ('token', 'token'), ('section_number', 'section_number'), ('pos', 'pos'), ('is_rubric', 'is_rubric'), ('verse_cat', 'verse_cat'), ('speech_cat', 'speech_cat')], max_length=32, unique=True)),
                ('label', models.CharField(max_length=32)),
                ('tooltip', models.CharField(blank=True, max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
