# Generated by Django 2.2.4 on 2019-10-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0015_auto_20191022_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfacet',
            name='whitelist',
            field=models.TextField(blank=True, default='', help_text='one facet option per line. If empty all options are visible, otherwise only the supplied options are visible.'),
        ),
    ]
