# Generated by Django 3.0.10 on 2020-11-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_search', '0021_auto_20200416_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnotatedToken',
        ),
        migrations.DeleteModel(
            name='AutocompleteForm',
        ),
        migrations.DeleteModel(
            name='Lemma',
        ),
    ]
