version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  # this allows us to test the data_release app locally
  media_target:
    name: tvof-django_media_target


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tvof_local_django
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - .:/app:z
      - media_target:/media_target
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: tvof_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      # - local_postgres_data_backups:/backups:z
      - ./.volumes/local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    restart: unless-stopped

  kiln:
    build:
      context: .
      dockerfile: ./compose/production/kiln/Dockerfile
    image: tvof_local_kiln
    volumes:
      - ./tvof/media:/django_media:Z
    env_file:
      - ./.envs/.local/.kiln
    command: /start
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.9.1
    env_file:
      - ./.envs/.local/.elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    restart: unless-stopped

#  kibana:
#    image: kibana:7.9.1
#    depends_on:
#      - elasticsearch
#    env_file:
#      - ./.envs/.local/.kibana
#    ports:
#      - '5601:5601'
#    restart: unless-stopped
